name: Trigger auto deployment for container-app-piofrecm5ckzy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-piofrecm5ckzy-AutoDeployTrigger-575fd53b-219c-4ec2-80af-b72707c90ea6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPIOFRECM5CKZY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPIOFRECM5CKZY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPIOFRECM5CKZY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPPIOFRECM5CKZY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPIOFRECM5CKZY_REGISTRY_PASSWORD }}
          containerAppName: container-app-piofrecm5ckzy
          resourceGroup: shopathomeangularaae2a655
          imageToBuild: default/container-app-piofrecm5ckzy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


